### ISSUE TITLE
Service configuration - ToU for service usage

### ISSUE THREAD

**Issue by ekmatts1** [OpusCapita/einvoice-send#100]
![11 service configuration_terms and condition for the service usage_acceptance](https://user-images.githubusercontent.com/28104515/30648868-5c946fbc-9e1f-11e7-9d6f-e1b1ef2b0775.png)
![12 service configuration_terms and condition for the service usage_done](https://user-images.githubusercontent.com/28104515/30648877-60d7bc50-9e1f-11e7-93c3-24803425aa2b.png)

**Comment by nczeranka** [comment]
Has changed in the meantime.
