### ISSUE TITLE
Dashboard - Supplier view (icon + view with invoices)

### ISSUE THREAD

**Issue by ekmatts1** [OpusCapita/einvoice-send#101]
![13 home_page_supplier](https://user-images.githubusercontent.com/28104515/30648927-818c6e78-9e1f-11e7-9c1a-4273d0d7cbbb.png)
![14 home_page_supplier_invoice_view](https://user-images.githubusercontent.com/28104515/30648944-85e0157e-9e1f-11e7-965a-5885dfd32601.png)

**Comment by nczeranka** [comment]
UI changed generally.
