### ISSUE TITLE
Create Invoice - header, line level, dataset, send 

### ISSUE THREAD

**Issue by ekmatts1** [OpusCapita/einvoice-send#102]
![16 create_invoice_invoice_header](https://user-images.githubusercontent.com/28104515/30649310-3a0df174-9e20-11e7-96d8-3e33da77dcc4.png)

**Comment by ekmatts1** [comment]
![17 create_invoice_invoice_header_information](https://user-images.githubusercontent.com/28104515/30649336-49ae2b4e-9e20-11e7-8da5-f6c83af4f6d6.png)

**Comment by ekmatts1** [comment]
![18 save_proceed_linelevel_items](https://user-images.githubusercontent.com/28104515/30649377-6933e35a-9e20-11e7-8744-0c25a6a65ed2.png)

**Comment by ekmatts1** [comment]
![19 fill in line level data](https://user-images.githubusercontent.com/28104515/30649422-873b3c90-9e20-11e7-84b5-22be1290b88e.png)

**Comment by nczeranka** [comment]
Approach is slightly different, but implemented in contact with Heikki.
