### ISSUE TITLE
Implement supplier capabilities creation / deletion 

### ISSUE THREAD

**Issue by lasong** [OpusCapita/einvoice-send#133]
- Once supplier has setup inChannelConfig fully, we need to call supplier to create the capability eInvoice. Method: `POST`, Endpoint: `/api/suppliers/:supplierId/capabilities/:capabilityId`, Body: (not needed)
- If supplier loses inChannelConfig (status change from approved), do the DELETE capability api call. Method: `DELETE`, Endpoint: `/api/suppliers/:supplierId/capabilities/:capabilityId`

Capability id: `eInvoice-send`

**Comment by nczeranka** [comment]
Though we currently do not support something like deleting the InChannel config, concentrate on calling the first endpoint.
