### ISSUE TITLE
Key-In configuration: Ui adjustments

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/einvoice-send#142]
Requirements from PM:
- Page 1: Remove Pdf part and Checkbox. Button: "Next"
- Page 3: New texts  - to be defined by PM

**Comment by OKSALTA1** [comment]
Page 2: New text.

Next steps

All required steps for the registration are done and you are soon able to send your first invoice through Invoice Key-in.
Before you can start using the Key-in tool we kindly ask you to go back to the start page and update your General Company information including Bank account where you wish to receive the payment.

**Comment by nczeranka** [comment]
Implemented (with the new English text, but without German translation) and installed on Prod.
