### ISSUE TITLE
Implement customer contracts

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/einvoice-send#3]
To be able to send invoice to a customer, we need an active contract.
This requires customer side approval.
Basically the flow is:
1. Explicit "connect"
    1. Supplier connects to customer of choice (Create einvoiceSendContract)
    2. Customer gets approval request (status update)
    3. Customer approves (status update to live = link is active for production)
2. Implicit "connect", via customer onboariding campaign
    1. Supplier eInvoiceSendContract is created in service config flow after base service setup
    2. Customer approval is implicit
    3. Contract is live immediately

So the domain will look like

eInvoiceSendContract
* supplierId String 
* customerId String (composite key with supplierId) 
* status String (lifecycle tracking)
* ... configuration fields

**Comment by nczeranka** [comment]
Is replaced with BusinessLinks. Old structures will be removed via #181
