### ISSUE TITLE
After Invoice intention confirmation: show additional info text

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/einvoice-send#51]
To clarify the next steps for the user after confirmation of his intention concerning einvoice, we have to show an extra info text to him (two paragraphs per language):
en: "Your decision is saved."
"Please proceed with completing you inchannel configuration with the available options"
de: "Ihre Erklärung bzgl. der zukünftigen Nutzung der eInoice-Anbindung ist gespeichert."
"Bitte vervollständigen Ihre Anbindungsdefinition über die Ihnen zur Verfügung stehenden Optionen."

Button:
en: "Continue"
de: "Fortfahren"

**Comment by RDeau** [comment]
watch the typos in original en paragraph:
decission -> decision and you inchannel -> your inchanneltion with the available options"
