### ISSUE TITLE
New menu item Invoice Key-In (icon+text)

### ISSUE THREAD

**Issue by ekmatts1** [OpusCapita/einvoice-send#97]
![5 new_menu_item_invoice_key_in](https://user-images.githubusercontent.com/28104515/30648644-d07cb746-9e1e-11e7-831c-54dd6af4788b.png)

**Comment by ekmatts1** [comment]
Under new menu item "Invoice Key-In there will be a sub menu - "Create"
![15 new_menu_item_invoice_key_sub_create](https://user-images.githubusercontent.com/28104515/30649019-c136f84a-9e1f-11e7-8674-8560dcf326ee.png)

**Comment by nczeranka** [comment]
Has changed in the meantime.
